#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create the custom 404 error page
sudo sh -c 'echo "<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>404 Not Found</h1><p>Ceci n'"'"'est pas une page</p></body></html>" > /usr/share/nginx/html/404.html'

# Configure Nginx to use the custom error page for 404 errors
sudo sed -i 's/#error_page 404/error_page 404 \/404.html;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx

# Display success message
echo "Nginx configured to serve custom 404 error page."

